
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

name: build-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang-
    - run: go env
    - name: go build
      run: go build -v ./...
    - name: go test
      run: go test -v ./...
    - name: build paw
      run: go build -o paw -v ./cmd/paw
    - name: Upload lord binary
      uses: actions/upload-artifact@v3
      with:
        name: paw-bin
        path: paw
